[build]
  publish = "public"
  functions = "netlify/functions"

[[redirects]]
  from = "/api/clients"
  to = "/.netlify/functions/clients"
  status = 200

[[redirects]]
  from = "/api/notify"
  to = "/.netlify/functions/notify"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
